# -*- mode: org;  -*-
#+AUTHOR: Simon Johnston
#+EMAIL: johnstonskj@gmail.com
#+LANGUAGE: en
#+STARTUP: overview hidestars inlineimages entitiespretty
#+OPTIONS: num:t toc:2

This is a simple *ox-html* setup file that implements a clean, modern look and feel similar to that provided by a modern
word processor such as MS Word. The typography is intended to bridge screen and print without too many changes and
relies on the Fira Sans for text and Fira Code for pre-formatted and code content.

Generation of the files from this source is via the ~org-babel-tangle~ function, or =C-c C-v t=, which tangles all the code
blocks into corresponding CSS, JavaScript, and setup files.

* Generated Top-Level Structure

#+CAPTION: Org-Exported TOC
#+BEGIN_SRC html :tangle no
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
  <head>...</head>
  <body>
    <div id="org-div-home-and-up">...</div>
    <div id="table-of-contents" role="doc-toc">
    <header>...</header>
    <nav  id="table-of-contents" role="doc-toc">...</nav>
    ...
    </div>
    <div id"postamble" class="status">...</div>
  </body>
</html>
#+END_SRC

* CSS
:PROPERTIES:
:header-args: :tangle office.css
:END:

All CSS content will be written to the file =office.css= which is referenced by the =office.setup= and =office-local.setup=
files.

** Typography

This block imports the two major fonts used in this theme. It also sets up variables for the specific weights and their
mapping to their usage.

#+BEGIN_SRC css
@import url('https://fonts.googleapis.com/css2?family=Fira+Code:wght@300;400;600&family=Fira+Sans:ital,wght@0,100;0,200;0,400;0,600;0,700;1,100;1,200;1,400;1,600;1,700&display=swap');
:root {
    --code-font-family: 'Fira Code', monospace;
    --code-weight-normal: 300;
    --code-weight-semibold: 400;
    --code-weight-bold: 600;

    --text-font-family: 'Fira Sans', 'Helvetica Neue', Arial, sans-serif;
    --text-weight-light: 100;
    --text-weight-normal: 200;
    --text-weight-heading: 400;
    --text-weight-bold: 600;
    --text-weight-heavy: 700;
}
#+END_SRC

This block is included to setup font features globally.

#+BEGIN_SRC css
html {
    -ms-text-size-adjust: 100%;
    -webkit-text-size-adjust: 100%;
    font-kerning: normal;
    font-size: 100%;
    height: 100%;
}
#+END_SRC

*** Colors

These are the base colors used throughout; local names introduced in sections below should shadow these values not add
additional colors without *really good* reasons.

#+BEGIN_SRC css
:root {
    --text-color: #3c484e;
    --title-color: #365F91;
    --subtitle-color: #808080;
    --heading-color: #4F81BD;
    --border-color: #A0A0A0;
    --code-color: #3c484e;
    --code-background-color: #f0f0f0;
    --code-border-color: #e8e8e8;
}
#+END_SRC

*** <<sec:relative-sizes>>Relative Sizes

These may be used not only for font sizing but for margins and padding also.

#+BEGIN_SRC css
:root {
    --text-normal: 1.0em;
    --text-small: 0.8em;
    --text-smaller: 0.6em;
    --text-tiny: 0.4em;
    --text-large: 1.6em;
    --text-larger: 2.4em;
    --text-huge: 3.2em;

    --line-height-none: 0;
    --line-height-normal: 1.6em;
    --line-height-code: 1.4em;
    --line-height-compressed: 1.2em;
    --line-extension-normal: 0.6em;
    --line-extension-code: 0.4em;
    --line-extension-compressed: 0.2em;
}
#+END_SRC

*** Body Content

#+BEGIN_SRC css
body {
    color: var(--text-color);
    font-family: var(--text-font-family);
    font-weight: var(--text-weight-normal);
    line-height: var(--line-height-normal);
}
#+END_SRC

#+BEGIN_SRC css
p, li, dd {
    text-align: justify;
}
#+END_SRC

*** Text Styles

Set what it means to be bold.

#+BEGIN_SRC css
b, strong {
    font-weight: var(--text-weight-bold);
}
#+END_SRC

*** Headings

#+CAPTION: Org-Exported Header
#+BEGIN_SRC html :tangle no
<header>
  <h1 class="title">
    ...
    <span class="subtitle">...</span>
  </h1>
</header>
#+END_SRC

The front-page title should be rather larger than normal.

#+BEGIN_SRC css
header > h1.title {
    color: var(--title-color);
    font-size: var(--text-larger);
    font-weight: var(--text-weight-heading);
    text-align: center;
}
#+END_SRC

Although the embedded subtitle should appear diminished.
#+BEGIN_SRC css
header > p.subtitle {
    color: var(--subtitle-color);
    font-size: var(--text-large);
    font-weight: var(--text-weight-heading);
    text-align: center;
}
#+END_SRC

The rest of the headings should share common colors and weight only.

#+BEGIN_SRC css
h1, h2, h3, h4, h5 {
    color: var(--heading-color);
    font-weight: var(--text-weight-heading);
}
#+END_SRC

*** Captions

As these properties are used to construct code, figure/image, and table captions it's worth naming them specifically.

#+BEGIN_SRC css
:root {
    --caption-font-size: var(--text-small);
    --caption-font-style: italic;
    --caption-font-weight: var(--text-weight-light);
}
#+END_SRC

*** Borders and Rules

These are some simple reusable values across table and block borders as well as ~<hr>~ elements.

#+BEGIN_SRC css
:root {
    --border-width: 1px;
    --border-width-thick: 2px;
    --border-width-block: 0.25em;
    --border-radius-small: 3px;
    --border-radius-normal: 0.25em;
    --border-style: solid;
    --table-border: var(--border-width) var(--border-style) var(--border-color);
    --section-border: var(--border-width) var(--border-style) var(--border-color);
}
#+END_SRC

** Media Queries

*** Screen

#+BEGIN_SRC css
@media screen {
    :root {
        --root-font-size-small: 14px;
        --root-font-size-normal: 16px;
        --root-font-size-large: 18px;
        --abstract-margin: calc(var(--text-huge) * 2);;
    }
}
#+END_SRC

#+BEGIN_SRC css
body {
    min-height: 100%;
    padding-left: var(--text-large);
    padding-right: var(--text-large)
}
h1.title {
    margin-top: var(--text-normal);
    margin-bottom: var(--text-smaller);
}
#+END_SRC

For mobile devices.

#+BEGIN_SRC css
@media screen and (min-width: 320px) and (max-width: 480px) {
    body {
        font-size: var(--root-font-size-small);
    }
    div#content {
        margin-left: auto;
        margin-right: auto;
        min-width: 21em;
        max-width: 30em;
    }
    img {
        max-width: 420px;
        height: auto;
    }
}
#+END_SRC

For common tablet devices.

#+BEGIN_SRC css
@media screen and (min-width: 481px) and (max-width: 768px)  {
    body {
        font-size: var(--root-font-size-small);
    }
    div#content {
        margin-left: auto;
        margin-right: auto;
        min-width: 30em;
        max-width: 48em;
    }
    img {
        max-width: 640px;
        height: auto;
    }
}
#+END_SRC

For small laptop or large tablet devices.

#+BEGIN_SRC css
@media screen and (min-width: 769px) and (max-width: 1024px)  {
    body {
        font-size: var(--root-font-size-normal);
    }
    div#content {
        margin-left: auto;
        margin-right: auto;
        min-width: 28em;
        max-width: 58em;
    }
    img {
        max-width: 100%;
        height: auto;
    }
}
#+END_SRC

For large laptop or desktop devices.

#+BEGIN_SRC css
@media screen and (min-width: 1025px) and (max-width: 2048px) {
    body {
        font-size: var(--root-font-size-large);
    }
    div#content {
        margin-left: auto;
        margin-right: auto;
		  min-width: 52em;
        max-width: 68em;
    }
    img {
        max-width: 100%;
        height: auto;
    }
}
#+END_SRC

For large displays.

#+BEGIN_SRC css
@media screen and (min-width: 2049px) {
    body {
        font-size: var(--root-font-size-large);
    }
    div#content {
        margin-left: auto;
        margin-right: auto;
        min-width: 68em;
        max-width: 72em;
    }
    img {
        max-width: 100%;
        height: auto;
    }
}
#+END_SRC

*** Print

#+BEGIN_SRC css
@media print {
    :root {
        --root-font-size-small: 12px;
        --root-font-size-normal: 14px;
        --root-font-size-large: 16px;
        --print-margin-inner: 4cm;
        --print-margin-outer: 2cm;
        --print-margin-top: var(--print-margin-outer);
        --print-margin-bottom: var(--print-margin-inner);
        --print-margin-equal: calc((var(--print-margin-outer) + var(--print-margin-inner)) / 2);
        --abstract-margin: var(--text-huge)
    }
}
#+END_SRC

#+BEGIN_SRC css
@media print {    
    body {
        font-size: var(--root-font-size-normal) !important;
        padding: 0 !important;
    }
    body.small-print {
        font-size: var(--root-font-size-small) !important;
        padding: 0 !important;
    }
    body.large-print {
        font-size: var(--root-font-size-large) !important;
        padding: 0 !important;
    }
    header > h1.title {
        margin-top: var(--text-huge);
        margin-bottom: var(--text-small);
    }
    header > p.subtitle {
        margin-top: var(--line-height-none);
        margin-bottom: var(--text-larger);
    }
    div#org-div-home-and-up {
        display: none;
    }
    nav#table-of-contents {
        display: none;
    }
    img {
        max-width: 100%;
        height: auto;
    }
    div#content {
        margin: auto;
    }
}
#+END_SRC

#+BEGIN_SRC css
@media print {
    h1.title { 
        string-set: doctitle content(); 
    }
    header, div.figure, td, th {
        page-break-inside: avoid;
    } 
    @page {
        size: letter portrait;
        margin-top:var(--print-margin-top);
        margin-bottom: var(--print-margin-equal);
    }
    @page :first {
        margin-left: var(--print-margin-equal);
        margin-right: var(--print-margin-equal);
    }
    @page :left {
        margin-left: var(--print-margin-outer);
        margin-right: var(--print-margin-inner);
        @bottom-left {
            content: counter(page);
        }
        @top-left {
            content: string(doctitle);
        }
    }
    @page :right {
        margin-left: var(--print-margin-inner);
        margin-right: var(--print-margin-outer);
        @bottom-right {
            content: counter(page);
        }
        @top-right {
            content: string(doctitle);
        }
    }
}
#+END_SRC

See also:

- https://www.w3.org/TR/css-page-3/#margin-boxes
- https://www.smashingmagazine.com/2015/01/designing-for-print-with-css/
- https://printcss.net/articles/page-margin-boxes
- https://printcss.net/articles/running-headers-and-footers

** Lists

Uses class =org-ol= and =org-ul=.

#+BEGIN_SRC css
ol li:last-child, ul li:last-child {
    margin-bottom: var(--text-small);
}
#+END_SRC

Uses class =org-dl=.

#+BEGIN_SRC css
:root {
    --dl-term-width-normal: 8em;
    --dl-term-width-wide: calc(var(--dl-term-width-normal) * 2);

    --dl-padding-normal: var(--text-normal);
}
#+END_SRC

#+BEGIN_SRC css
dl.org-dl {
    display: grid;
    grid-template-columns: max-content auto;
    gap: var(--dl-padding-normal);
}
#+END_SRC

#+BEGIN_SRC css
dl.org-dl > dt {
    grid-column-start: 1;
    font-weight: var(--code-weight-semibold);
}
dl.org-dl > dt {
    max-width: var(--dl-term-width-normal);
    min-width: calc(var(--dl-term-width-normal) * 0.75)
}
dl.org-dl.wide > dt {
    max-width: var(--dl-term-width-wide);
    min-width: calc(var(--dl-term-width-wide) * 0.75)
}
#+END_SRC

#+BEGIN_SRC css
dl.org-dl > dd {
    grid-column-start: 1;
}
#+END_SRC

** Blocks

*** Abstract

#+BEGIN_SRC css
div.abstract, div.ABSTRACT {
    font-size: var(--text-small);
    margin-top: var(--text-huge);
    margin-left: var(--abstract-margin);
    margin-right: var(--abstract-margin);
    margin-bottom: var(--text-large);
}

div.abstract > p::before, div.ABSTRACT > p::before {
    content: "Abstract: ";
    font-weight: var(--text-weight-heading);
}
#+END_SRC

*** Table of Contents

#+CAPTION: Org-Exported TOC
#+BEGIN_SRC html :tangle no
<nav id="table-of-contents" role="doc-toc">
  <h2>Table of Contents</h2>
  <div id="text-table-of-contents" role="doc-toc">
    <ul>
      <li><a href="#org289a925">1. Basic Terms</a>
        <ul>
          <li><a href="#org98111a5">1.1. Data Model</a></li>
        </ul>
      </li>
      <li><a href="#org7bc4e5f">2. Collection Resources</a></li>
    </ul>
  </div>
</nav>
#+END_SRC

#+BEGIN_SRC css
nav#table-of-contents > div#text-table-of-contents ul {
    list-style-type: none;
    margin-left: var(--text-normal);
    padding: 0;
}
#+END_SRC

*** Block Quotes

#+BEGIN_SRC css
#+END_SRC

*** Notes

#+BEGIN_SRC css
div.NOTE {
    margin: var(--text-normal);
    padding: var(--text-normal);
    border: var(--border-width-thick) var(--border-style) var(--heading-color);
    border-radius: var(--border-radius-normal);
}

div.NOTE p {
    margin-block-start: 0;
    margin-block-end: 0;
}

div.NOTE p::before {
    content: "Note: ";
    font-weight: var(--text-weight-heading);
}
#+END_SRC

** Images

Org-mode images are output by the HTML exporter according to the layout in the example shown below.

#+CAPTION: Org-Exported Figure
#+BEGIN_SRC html :tangle no
<figure id="org559bb8e">
  <img src="amethyst-ia.svg" alt="amethyst-ia.svg" class="org-svg">
  <figcaption>
    <span class="figure-number">Figure 1: </span>Amethyst Information Architecture
  </figcaption>
</figure>
#+END_SRC

First, we want all elements of the figure to be centered.

#+BEGIN_SRC css
figure {
    text-align: center;
    break-inside: avoid;
}
#+END_SRC

Setup the text style of the caption.

#+BEGIN_SRC css
figure > figcaption {
    font-size: var(--caption-font-size);
    font-style: var(--caption-font-style);
    font-weight: var(--caption-font-weight);
}
#+END_SRC

Bring the image and caption closer together.

#+BEGIN_SRC css
figure > img {
    margin-bottom: var(--text-tiny);
}
figure > figcaption {
    margin-top: 0;
}
#+END_SRC

** Tables

Org-mode tables are output by the HTML exporter according to the layout in the example shown below.

#+CAPTION: Org-Exported Table
#+BEGIN_SRC html :tangle no
<table border="0" cellspacing="0" cellpadding="6" rules="none" frame="none">
  <caption class="t-above">
    <span class="table-number">Table 2:</span> Some Table</caption>
  <colgroup>
    <col class="org-left">
    <col class="org-left">
  </colgroup>
  <thead>
    <tr>
      <th scope="col" class="org-left">Key</th>
      <th scope="col" class="org-left">Value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="org-left">key-1</td>
      <td class="org-left">value-1</td>
    </tr>
  </tbody>
</table>
#+END_SRC

Unlike the default exporter, and LaTeX style, /and/ general readability guidance, we put borders back on tables. It is
also generally useful to reduce the size of 

#+BEGIN_SRC css
table {
    border: var(--table-border);
    border-collapse: collapse;
    margin-left: auto;
    margin-right: auto;
    min-width: 50%;
    font-size: var(--text-small);
    line-height: var(--line-height-compressed);
    break-inside: avoid; 
}

table > thead {
    color: var(--heading-color);
    font-weight: var(--text-weight-heading);
}

table > thead th,
table > tbody td {
    border: var(--table-border);
}
#+END_SRC

#+BEGIN_SRC css
table > thead th.org-left,
table > tbody td.org-left {
    text-align: left;
}
table > thead th.org-center,
table > tbody td.org-center {
    text-align: center;
}
table > thead th.org-right,
table > tbody td.org-right {
    text-align: right;
}
#+END_SRC

Setup the caption for a table, this is a common set of properties for all captions.

#+BEGIN_SRC css
table caption {
    font-size: var(--caption-font-size);
    font-style: var(--caption-font-style);
    font-weight: var(--caption-font-weight);
}
#+END_SRC

** Code

Org-Export generates code of the following form. Note that it does not, as is more common, use a ~<code>~ element within
the ~<pre>~. The class ~src~ is common to all source blocks and any language specified on the source block generates a class
name of the form =src-{name}=.

#+BEGIN_SRC html :tangle no
<div class="org-src-container">
  <label class="org-src-name">
    <span class="listing-number">Listing 2: </span>Directory-Local Variables
  </label>
  <pre class="src src-elisp"> 
    <span style="color: #657b83;">(</span><span style="color: #657b83;">)</span>
  </pre>
</div>
#+END_SRC

#+BEGIN_SRC css
pre, code {
    font-family: var(--code-font-family);
    font-size: var(--text-small);
    font-weight: var(--code-weight-normal);
    line-height: var(--line-height-code);
}
#+END_SRC

#+BEGIN_SRC css
div.org-src-container {
    break-inside: avoid;
}
#+END_SRC

#+BEGIN_SRC css
div.org-src-container > pre.src {
    margin-top: var(--text-tiny);
    padding: var(--text-normal);
    background-color: var(--code-background-color);
    border: var(--border-width) var(--border-style) var(--code-border-color);
    border-radius: var(--border-radius-small);
    overflow-x: hidden;
}
#+END_SRC

#+BEGIN_SRC css
div.org-src-container > pre.src.scroll {
    overflow-x: scroll;
}
#+END_SRC

#+BEGIN_SRC css
p code, li code, dt code, dd code {
    background-color: var(--code-background-color);
    padding-left: var(--line-extension-compressed);
    padding-right: var(--line-extension-compressed);
}
#+END_SRC
    
#+BEGIN_SRC css
div.org-src-container > label.org-src-name {
    font-size: var(--caption-font-size);
    font-style: var(--caption-font-style);
    font-weight: var(--caption-font-weight);
}
#+END_SRC

** Math (KaTeX)

#+BEGIN_SRC css
:root {
    --math-color: var(--text-color);
    --math-font-size: 1.1em;
}
#+END_SRC

The /math font size/ is a specific value, not one of those defined in [[sec:relative-sizes]], as it is very dependent on the math renderer
(MathJax for example really needs a size less than =1.0em=) and some fine tuning as math fonts tend to have rounder
characters and so bringing the vertical heights close results in wide looking text.

The math color should match the body text color, by default it's black and tends to jump out,m especially as the weight
of the math font tends to be heavier.

#+BEGIN_SRC css
.katex {
    color: var(--math-color);
    font-size: var(--math-font-size);
}
#+END_SRC

Treat tags on equations in the same manner as captions.

#+BEGIN_SRC css
.katex .tag {
    font-size: var(--caption-font-size);
    font-style: var(--caption-font-style);
    font-weight: var(--caption-font-weight);
}
#+END_SRC

** Home and Up

#+BEGIN_SRC css
div#org-div-home-and-up {
    text-align: right;
    font-size: var(--text-smaller);
    white-space: nowrap;
}
#+END_SRC

** Footnotes and References

#+BEGIN_SRC css
div#footnotes {
    border-top: var(--section-border);
    font-size: var(--text-small);
}
#+END_SRC

** Postamble

#+BEGIN_SRC css
div#postamble {
    border-top: var(--section-border);
    margin-top: var(--text-larger);
    padding-top: var(--text-normal);
    font-weight: var(--text-weight-light);
    font-size: var(--text-small);
}
div#postamble > p {
    line-height: var(--line-height-compressed);
    margin-top: var(--text-tiny);
    margin-bottom: 0;
}

div#postamble > p.validation {
    display: none;
}
#+END_SRC

#+BEGIN_SRC css
#+END_SRC

* Javascript
:PROPERTIES:
:header-args: :tangle office.mjs
:END:

#+BEGIN_SRC js
"use strict";
#+END_SRC

** Math (KaTeX)

This allows you to add your own macros in the constant src_js[:exports code]{KATEX_MACROS}.

#+BEGIN_SRC js
import renderMathInElement from 'https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.mjs';

export function initMath(options) {
    const KATEX_MACROS = document.KATEX_MACROS || {};
    document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
            macros: KATEX_MACROS
        });
    });
}
#+END_SRC

* Setup File
:PROPERTIES:
:header-args: :tangle office.setup
:END:

Should be:

KaTeX requires the use of the HTML5 doctype; without it, KaTeX may not render properly. The loading of KaTeX is deferred
to speed up page rendering, and to automatically render math in text elements, include the auto-render extension.


#+BEGIN_SRC org
# -*- mode: org; -*-
,#+BEGIN_SRC emacs-lisp :exports none

,#+HTML_DOCTYPE: xhtml5
,#+OPTIONS: html-style:nil html5-fancy:t

,#+HTML_HEAD: <script nomodule
,#+HTML_HEAD:         defer
,#+HTML_HEAD:         src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.js"
,#+HTML_HEAD:         integrity="sha384-ImWHyYvDPlRzwFnvLhG9Jcpm/7qL4SVIuJK0C6Rj+Mf7fpeNJCLCynC+EVz4kCSA"
,#+HTML_HEAD:         crossorigin="anonymous"></script>
,#+HTML_HEAD: <script nomodule
,#+HTML_HEAD:         defer
,#+HTML_HEAD:         src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js"
,#+HTML_HEAD:         integrity="sha384-+VBxd3r6XgURycqtZ117nYw44OOcIax56Z4dCRWbxyPt0Koah1uHoK0o4+/RRE05"
,#+HTML_HEAD:         crossorigin="anonymous"></script>
,#+HTML_HEAD: <link rel="stylesheet"
,#+HTML_HEAD:       href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css"
,#+HTML_HEAD:       integrity="sha384-n8MVd4RsNIU0tAv4ct0nTaAbDJwPJzDEaqSD1odI+WdtXRGWt2kTvGFasHpSy3SV"
,#+HTML_HEAD:       crossorigin="anonymous">
,#+HTML_HEAD: 
,#+HTML_HEAD: <link rel="stylesheet"
,#+HTML_HEAD:       href="https://simonkjohnston.life/org-export-themes/html/office/office.css">
,#+HTML_HEAD: <script type="module" type="text/javascript">
,#+HTML_HEAD:     import initMath from 'https://simonkjohnston.life/org-export-themes/html/office/office.mjs';
,#+HTML_HEAD:     initMath();
,#+HTML_HEAD: </script>
#+END_SRC

** Local Install
:PROPERTIES:
:header-args: :tangle office-local.setup
:END:

#+BEGIN_SRC org
# -*- mode: org; -*-
,#+BEGIN_SRC emacs-lisp :exports none

,#+HTML_DOCTYPE: xhtml5
,#+OPTIONS: html-style:nil html5-fancy:t mathjax-template:nil

,#+HTML_HEAD: <link rel="stylesheet"
,#+HTML_HEAD:       href="./themes/office/office.css">
,#+HTML_HEAD: <link rel="stylesheet"
,#+HTML_HEAD:       href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css"
,#+HTML_HEAD:       integrity="sha384-n8MVd4RsNIU0tAv4ct0nTaAbDJwPJzDEaqSD1odI+WdtXRGWt2kTvGFasHpSy3SV"
,#+HTML_HEAD:       crossorigin="anonymous">

,#+HTML_HEAD: <script type="text/javascript"
,#+HTML_HEAD:         src="./themes/office/office.js"></script>
,#+HTML_HEAD: <script defer
,#+HTML_HEAD:         src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"
,#+HTML_HEAD:         integrity="sha384-XjKyOOlGwcjNTAIQHIpgOno0Hl1YQqzUOEleOLALmuqehneUG+vnGctmUb0ZY0l8"
,#+HTML_HEAD:         crossorigin="anonymous"></script>
,#+HTML_HEAD: <script defer
,#+HTML_HEAD:         src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js"
,#+HTML_HEAD:         integrity="sha384-+VBxd3r6XgURycqtZ117nYw44OOcIax56Z4dCRWbxyPt0Koah1uHoK0o4+/RRE05"
,#+HTML_HEAD:         crossorigin="anonymous"
,#+HTML_HEAD:         onload="renderMathInElement(document.body);"></script>
#+END_SRC
